/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 Leo Kuroshita (@kurogedelic), Hügelton Instruments */
/* MELODEE: one compilation unit (the HAL is header-only). Each file uses what the files above it
 * define, so the order matters. */

/* ---------------------------------------------------- build options --- */
/* build.py: MELODEE_<NAME>=0 / 1 in the environment overrides these. Elsewhere: MELODEE_SLICE, MELODEE_FM4
 * (core.h: the SLICE engine, the DIGITAL engine), MELODEE_ICONS (icons.c, the parameter icons; on by default),
 * MELODEE_OTA_RAMONLY (ota.c). */
#include "build_options.h"      /* defaults shared with crt0.S */
#ifndef MELODEE_CACHE_RAM
#define MELODEE_CACHE_RAM 1     /* seven data-cache ways as RAM after a boot self-test (MELODEE_CACHE_RAM=0: off) */
#endif
#ifndef MELODEE_CORE1_TEST
#define MELODEE_CORE1_TEST 0    /* editor command 79 injects CPU1 failures (tools/core1_fault_test.py); never release */
#endif
#ifndef MELODEE_FLASH
#define MELODEE_FLASH 1         /* flash driver + storage.c: settings, projects, user presets */
#endif
#ifndef MELODEE_OTA
#define MELODEE_OTA 1            /* M-UPGRADE update entry and the editor SysEx; needs MELODEE_FLASH */
#endif
#ifndef MELODEE_OTA_DRYRUN
#define MELODEE_OTA_DRYRUN 0     /* 1 = stage, ask "success", then undo: no record, no reset */
#endif
#ifndef MELODEE_USB_AUDIO
#define MELODEE_USB_AUDIO 1      /* USB audio (usb_audio.c): "Melodee Out" plays through the FM-1, "Melodee In"
                                  * records the four tracks; 16 / 24 bit, 44.1 kHz. Needs EP2 / EP3: no CDC */
#endif
#ifndef MELODEE_CDC
#define MELODEE_CDC !MELODEE_USB_AUDIO   /* USB CDC-ACM serial console */
#endif
#ifndef MELODEE_UART
#define MELODEE_UART 1           /* TRS MIDI IN on UART1 / PH8 */
#endif
#ifndef MELODEE_ID
#define MELODEE_ID "FM-1_900"    /* package identity (build.py: the .fwsc marker string) */
#endif
#ifndef MELODEE_VERSION
#define MELODEE_VERSION "v1.0.2" /* shown in the menu, the console and the editor; build.py --release X.Y[.Z] */
#endif
#if MELODEE_OTA && !MELODEE_FLASH
#error "MELODEE_OTA needs MELODEE_FLASH"
#endif

/* ------------------------------------------------------------- HAL --- */
#include <stdint.h>
#include "fm1_time.h"
#include "fm1_sys.h"
#include "fm1_power.h"
#include "fm1_irq.h"
#include "fm1_guard.h"
#include "fm1_cache.h"
#if MELODEE_DUAL_CORE
#include "fm1_multicore.h"
#endif
#include "fm1_input.h"
#include "fm1_timer.h"
#include "fm1_audio.h"
#include "fm1_adc.h"
#include "fm1_lcd_hw.h"
#include "melodee_tables.h"      /* generated by build.py (tools/gen_tables.py) */

/* ----------------------------------------------------- base, display --- */
#include "libc.c"
#include "lcd.c"
#include "gfx.c"

/* ----------------------------------------------------------- sound --- */
#include "core.h"
#include "engines.c"             /* dsp.c, the eng_*.c files, the factory patterns */
#include "params.c"
#include "mod.c"               /* the modulation matrix, used by voice.c and fx.c */
#include "voice.c"
#include "slicer.c"              /* per-track SLICER insert, used by fx.c */
#include "fx.c"

/* ------------------------------------------------- MIDI, sequencer --- */
#define MIDI_TIME_NOW() fm1_ticks()
#define MIDI_TICKS_PER_MS (1000u * FM1_TICKS_PER_US)
#include "usb.c"
#if MELODEE_UART
#include "midi_uart.c"
#endif
#include "song_chain.c"
#include "seq.c"
#include "audio.c"

/* -------------------------------------------------------------- UI --- */
#include "panel.c"
#include "ui.c"
#include "icons.c"               /* parameter icons (MELODEE_ICONS), used by ui_draw.c */
#include "ui_graph.c"
#include "ui_draw.c"
#include "ui_menu.c"
#include "ui_input.c"
#include "ui_layer.c"              /* the quick layers (FX GLO SCL EDIT held) */

/* --------------------------------------------- storage, update, editor --- */
#if MELODEE_FLASH
#include "fm1_flash.h"
#include "storage_hw.c"
#include "storage.c"
#endif
#include "upreset.c"             /* user presets (RAM mirror; flash with MELODEE_FLASH) */
#include "project.c"
#include "cz_store.c"
#include "fm6_store.c"            /* FM6: DX7 SysEx, the STORE shortcut to user presets */
#if MELODEE_OTA
#include "ota.c"
#include "ota_hw.c"
#include "editor.c"              /* web editor SysEx (needs the OTA SysEx plumbing) */
#endif
#if MELODEE_CDC
#include "console.c"
#endif
#include "main.c"
